// Services
export { AuthService } from './services/auth.service'
export { AlertService } from './services/alert.service'
export { CommentService } from './services/comment.service'
export { UserService } from './services/user.service'
export { UserProfilePhotoService } from './services/user-profile-photo.service'
export { NotificationService } from './services/notification.service'
export { ClientCompanyService } from './services/client-company.service'
export { SiteService } from './services/site.service'
export { CompanyService } from './services/company.service'
export { AssetService } from './services/asset.service'
export { ClientWorkOrderService } from './services/client-work-order.service'
export { EmailConfigurationService } from './services/email-configuration.service'
export { EmailTemplateService } from './services/email-template.service'
export { EmailSenderService } from './services/email-sender.service'
export { FeatureService } from './services/feature.service'
export { AttendanceService } from './services/attendance.service'
export { LocationService } from './services/location.service'

// Repositories
export { AlertRepository } from './repositories/alert.repository'
export { CommentRepository } from './repositories/comment.repository'
export { UserRepository } from './repositories/user.repository'
export { ClientCompanyRepository } from './repositories/client-company.repository'
export { SiteRepository } from './repositories/site.repository'
export { CompanyRepository } from './repositories/company.repository'
export { AssetRepository } from './repositories/asset.repository'
export { EmailConfigurationRepository } from './repositories/email-configuration.repository'
export { EmailTemplateRepository } from './repositories/email-template.repository'
export { FeatureRepository } from './repositories/feature.repository'
export { AttendanceRepository } from './repositories/attendance.repository'
export { LocationRepository } from './repositories/location.repository'

// Helpers
export { PermissionHelper } from './helpers/permission.helper'

// Re-export types from the main types folder
export type { AuthenticatedSession, User } from '@/types/auth.types'
export type { AlertWithRelations, AlertFilters, PaginatedAlertsResponse, CreateAlertData, UpdateAlertData } from '@/types/alert.types'
export type { CommentWithAuthor, CreateCommentData } from '@/types/comment.types'
export type { UserWithRelations, UserFilters, PaginatedUsersResponse, CreateUserData, UpdateUserData } from '@/types/user.types'
export type { ClientCompanyWithRelations, ClientCompanyFilters, PaginatedClientCompaniesResponse, CreateClientCompanyData, UpdateClientCompanyData } from '@/types/client-company.types'
export type { SiteWithRelations, SiteFilters, PaginatedSitesResponse, CreateSiteData, UpdateSiteData } from '@/types/site.types'
export type { CompanyWithRelations, CompanyBranding, CompanyBasicInfo, CompanyFilters, PaginatedCompaniesResponse, CreateCompanyData, UpdateCompanyData } from '@/types/company.types'
export type { AssetWithRelations, AssetFilters, PaginatedAssetsResponse, CreateAssetData, UpdateAssetData } from '@/types/asset.types'
export type { EmailConfigurationWithRelations, EmailTemplateWithRelations, EmailTemplateType, CreateEmailConfigurationData, UpdateEmailConfigurationData, CreateEmailTemplateData, UpdateEmailTemplateData, PaginatedEmailConfigurationsResponse, PaginatedEmailTemplatesResponse } from '@/types/email.types'

// Re-export schemas
export { createUserSchema, updateUserSchema, userFiltersSchema } from '@/app/api/schemas/user-schemas'
export { createClientCompanySchema, updateClientCompanySchema, clientCompanyFiltersSchema } from '@/app/api/schemas/client-company-schemas'
export { createSiteSchema, updateSiteSchema, siteFiltersSchema } from '@/app/api/schemas/site-schemas'
export { createCompanySchema, updateCompanySchema, companyFiltersSchema, brandingQuerySchema } from '@/app/api/schemas/company-schemas'
export { createAssetSchema, updateAssetSchema, assetFiltersSchema } from '@/app/api/schemas/asset-schemas'
export { createEmailConfigurationSchema, updateEmailConfigurationSchema, emailConfigurationFiltersSchema, createEmailTemplateSchema, updateEmailTemplateSchema, emailTemplateFiltersSchema, emailTemplateTypeEnum } from '@/app/api/schemas/email-schemas'